slogan: "Welcome To Slackware Linux CN Community."

menu:
  - title: 归档
    url: archives
    #intro: ""
    icon: "fa fa-archive"
  - title: 关于
    url: About
    #intro: "About me."
    icon: "fa fa-user"
  - title: 加入我们
    url: JoinUs
    #intro: "About me."
    icon: "fa fa-user"
  - title: RSS
    url: atom.xml
    intro: "Subscribe me."
    icon: "fa fa-user"

links:
  - title: Slackware Linux
    url: http://www.slackware.com
    intro: "The Slackware Linux Project"
  - title: Security Mail List
    url: http://www.slackware.com/security
    intro: "Slackware 安全通知"
  - title: SlackDocs
    url: http://docs.slackware.com
    intro: "Slackare 文档"
  - title: The Slackware Linux CN Community
    url: https://github.com/slackwarecn
    intro: "Slackware 中文社区的 GitHub 组织"
  - title: SlackBuilds
    url: https://slackbuilds.org
    intro: "Slackware 用户社区贡献的软件包"
  - title: Alien's SlackBuilds
    url: http://www.slackware.com/~alien/slackbuilds
    intro: "部分 SlackBuilds 的二进制包"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: /atom.xml
fancybox: true
favicon: img/avatar.jpg
duoshuo_shortname: slackwarecn


# Analytics (change to yours)
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
